# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3.5"

networks:
  healthcare_network:
   name: healthcare_network

services:
  ca.solapurhcareorderer.in:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.solapurhcareorderer.in
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tls/tls-ca.solapurhealthcare.in-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/tls/tls-ca.solapurhealthcare.in.pem
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    # command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.solapurhealthcare.in-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/tls/tls-ca.solapurhealthcare.in.pem -b admin:adminpw -d'
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      # - ./organizations/fabric-ca/solapurhealthcare.in:/etc/hyperledger/fabric-ca-server-config
      # - ./organizations/fabric-ca/solapurhealthcare.in/tls:/etc/hyperledger/fabric-ca-server-config/tls
      - ./organizations/fabric-ca/solapurhealthcare.in:/etc/hyperledger/fabric-ca-server
    container_name: ca.solapurhcareorderer.in
    networks:
      - healthcare_network

  ca.scsmsr.co.in:
   image: hyperledger/fabric-ca:$IMAGE_TAG
   environment:
     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
     - FABRIC_CA_SERVER_CA_NAME=ca.scsmsr.co.in
     - FABRIC_CA_SERVER_TLS_ENABLED=true
    #  - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.scsmsr.co.in-cert.pem
    #  - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CSMSR_CA_PK}
     - FABRIC_CA_SERVER_PORT=8054
   ports:
     - "8054:8054"
   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
   volumes:
    #  - ./crypto-config/peerOrganizations/csmsr.gov.in/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./organizations/fabric-ca/scsmsr.co.in:/etc/hyperledger/fabric-ca-server
   container_name: ca.scsmsr.co.in
   networks:
     - healthcare_network

  ca.ashwinihospital.co.in:
   image: hyperledger/fabric-ca:$IMAGE_TAG
   environment:
     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
     - FABRIC_CA_SERVER_CA_NAME=ca.ashwinihospital.co.in
     - FABRIC_CA_SERVER_TLS_ENABLED=true
    #  - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ashwinihospital.co.in-cert.pem
    #  - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${ASHWINI_HOSPITAL_CA_PK}
     - FABRIC_CA_SERVER_PORT=9054
   ports:
     - "9054:9054"
   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
   volumes:
     - ./organizations/fabric-ca/ashwinihospital.co.in:/etc/hyperledger/fabric-ca-server
   container_name: ca.ashwinihospital.co.in
   networks:
     - healthcare_network
