# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3.5"

networks:
  healthcare_network:
   name: healthcare_network

services:
  solapur_healthcare_ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=solapur_healthcare_ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.solapurhealthcare.in-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${SOLAPUR_HEALTHCARE_CA_PK}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.solapurhealthcare.in-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${SOLAPUR_HEALTHCARE_CA_PK} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/solapurhealthcare.in/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: solapur_healthcare_ca
    networks:
      - healthcare_network

  #csmsr_ca:
  #  image: hyperledger/fabric-ca:$IMAGE_TAG
  #  environment:
  #    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #    - FABRIC_CA_SERVER_CA_NAME=csmsr_ca
  #    - FABRIC_CA_SERVER_TLS_ENABLED=true
  #    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.csmsr.gov.in-cert.pem
  #    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CSMSR_CA_PK}
  #    - FABRIC_CA_SERVER_PORT=8054
  #  ports:
  #    - "8054:8054"
  #  command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.csmsr.gov.in-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CSMSR_CA_PK} -b admin:adminpw -d'
  #  volumes:
  #    - ./crypto-config/peerOrganizations/csmsr.gov.in/ca/:/etc/hyperledger/fabric-ca-server-config
  #  container_name: csmsr_ca
  #  networks:
  #    - healthcare_network
#
  #ashwini_hospital_ca:
  #  image: hyperledger/fabric-ca:$IMAGE_TAG
  #  environment:
  #    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #    - FABRIC_CA_SERVER_CA_NAME=ashwini_hospital_ca
  #    - FABRIC_CA_SERVER_TLS_ENABLED=true
  #    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ashwinihospital.co.in-cert.pem
  #    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${ASHWINI_HOSPITAL_CA_PK}
  #    - FABRIC_CA_SERVER_PORT=7054
  #  ports:
  #    - "7054:7054"
  #  command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ashwinihospital.co.in-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${ASHWINI_HOSPITAL_CA_PK} -b admin:adminpw -d'
  #  volumes:
  #    - ./crypto-config/peerOrganizations/ashwinihospital.co.in/ca/:/etc/hyperledger/fabric-ca-server-config
  #  container_name: ashwini_hospital_ca
  #  networks:
  #    - healthcare_network
