
version: '3.5'

volumes:
  ashwinihospital.co.in:

networks:
  healthcare_network:
   name: healthcare_network

services:
  ashwinihospital.co.in:
    container_name: ashwinihospital.co.in
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=ashwinihospital.co.in
      - CORE_PEER_ADDRESS=ashwinihospital.co.in:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=ashwinihospital.co.in:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=ashwinihospital.co.in:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=ashwinihospital.co.in:9051
      - CORE_PEER_LOCALMSPID=AshwiniHospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../organizations/peerOrganizations/ashwinihospital.co.in/peers/ashwinihospital.co.in/msp:/etc/hyperledger/fabric/msp
        - ../../organizations/peerOrganizations/ashwinihospital.co.in/peers/ashwinihospital.co.in/tls:/etc/hyperledger/fabric/tls
        - ashwinihospital.co.in:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - healthcare_network
