
version: '3.5'

volumes:
  opd.ashwinihospital.co.in:
  anchor.ashwinihospital.co.in:
  orderer.ashwinihospital.co.in:

networks:
  healthcare_network:
   name: healthcare_network

services:
  couchdb.opd.ashwinihospital.co.in:
    container_name: couchdb.opd.ashwinihospital.co.in
    image: couchdb:3.1.1
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=opdashwinicouchdbadmin
      - COUCHDB_PASSWORD=opdashwinicouchdbadminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 5984:5984
    networks:
      - healthcare_network

  opd.ashwinihospital.co.in:
    container_name: opd.ashwinihospital.co.in
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=healthcare_network
      # - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=opd.ashwinihospital.co.in
      - CORE_PEER_ADDRESS=opd.ashwinihospital.co.in:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=opd.ashwinihospital.co.in:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=opd.ashwinihospital.co.in:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=opd.ashwinihospital.co.in:9051
      - CORE_PEER_LOCALMSPID=AshwiniHospitalMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.opd.ashwinihospital.co.in:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=opdashwinicouchdbadmin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=opdashwinicouchdbadminpw
    volumes:
        - /var/run/:/host/var/run/
        - ../../organizations/peerOrganizations/ashwinihospital.co.in/peers/opd.ashwinihospital.co.in/msp:/etc/hyperledger/fabric/msp
        - ../../organizations/peerOrganizations/ashwinihospital.co.in/peers/opd.ashwinihospital.co.in/tls:/etc/hyperledger/fabric/tls
        - opd.ashwinihospital.co.in:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on: 
      - couchdb.opd.ashwinihospital.co.in
    ports:
      - 9051:9051
      - 9052:9052
    networks:
      - healthcare_network

  anchor.ashwinihospital.co.in:
    container_name: anchor.ashwinihospital.co.in
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=healthcare_network
      # - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=anchor.ashwinihospital.co.in
      - CORE_PEER_ADDRESS=anchor.ashwinihospital.co.in:9053
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9053
      - CORE_PEER_CHAINCODEADDRESS=ashwinihospital.co.in:9055
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9055
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=anchor.ashwinihospital.co.in:9053
      - CORE_PEER_GOSSIP_BOOTSTRAP=anchor.ashwinihospital.co.in:9053
      - CORE_PEER_LOCALMSPID=AshwiniHospitalMSP
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.ashwinihospital.co.in:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=ashiwinicouchdbadmin
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=ashiwinicouchdbadminpw
    volumes:
        - /var/run/:/host/var/run/
        - ../../organizations/peerOrganizations/ashwinihospital.co.in/peers/anchor.ashwinihospital.co.in/msp:/etc/hyperledger/fabric/msp
        - ../../organizations/peerOrganizations/ashwinihospital.co.in/peers/anchor.ashwinihospital.co.in/tls:/etc/hyperledger/fabric/tls
        - anchor.ashwinihospital.co.in:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9053:9053
      - 9055:9055
    networks:
      - healthcare_network

  orderer.ashwinihospital.co.in:
    container_name: orderer.ashwinihospital.co.in
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=AshwiniHospitalMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ashwinihospital-ca-chain.pem,/var/hyperledger/orderer/tls/scsmsr-ca-chain.pem]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ashwinihospital-ca-chain.pem,/var/hyperledger/orderer/tls/scsmsr-ca-chain.pem]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../../organizations/ordererOrganizations/orderer.ashwinihospital.co.in/orderers/orderer.ashwinihospital.co.in/msp:/var/hyperledger/orderer/msp
        - ../../organizations/ordererOrganizations/orderer.ashwinihospital.co.in/orderers/orderer.ashwinihospital.co.in/tls/:/var/hyperledger/orderer/tls
        - orderer.ashwinihospital.co.in:/var/hyperledger/production/orderer
    ports:
      - 8050:8050
    networks:
      - healthcare_network

  orderer.ashwinihospital.co.in1:
    container_name: orderer.ashwinihospital.co.in
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=AshwiniHospitalOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../../organizations/ordererOrganizations/orderer.ashwinihospital.co.in/orderers/orderer.ashwinihospital.co.in/msp:/var/hyperledger/orderer/msp
        - ../../organizations/ordererOrganizations/orderer.ashwinihospital.co.in/orderers/orderer.ashwinihospital.co.in/tls/:/var/hyperledger/orderer/tls
        - orderer.ashwinihospital.co.in:/var/hyperledger/production/orderer
    ports:
      - 8050:8050
    networks:
      - healthcare_network
