# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3.5"

networks:
  healthcare_network:
   name: healthcare_network

services:


  ca.ashwinihospital.co.in:
   image: hyperledger/fabric-ca:$IMAGE_TAG
   environment:
     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
     - FABRIC_CA_SERVER_CA_NAME=ca.ashwinihospital.co.in
     - FABRIC_CA_SERVER_TLS_ENABLED=true
     - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server/tls/server.key
     - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server/tls/server.crt
     - FABRIC_CA_SERVER_TLS_CLIENTAUTH_TYPE=VerifyClientCertIfGiven
     - FABRIC_CA_SERVER_TLS_CLIENTAUTH_CERTFILES=/etc/hyperledger/fabric-ca-server/tls/ca.crt
     - FABRIC_CA_SERVER_INTERMEDIATE_PARENTSERVER_URL=https://admin.ashwiniCA:admin.ashwiniCApw@ca.solapurhcareorderer.in:7054
     - FABRIC_CA_SERVER_INTERMEDIATE_PARENTSERVER_CANAME=ca.solapurhcareorderer.in
     - FABRIC_CA_SERVER_PORT=9054
   ports:
     - "9054:9054"
   command: sh -c 'fabric-ca-server init -b admin:adminpw && ls /etc/hyperledger/fabric-ca-server/msp/keystore && fabric-ca-server start -b admin:adminpw -d'
   volumes:
     - ../../../organizations/fabric-ca/ashwinihospital.co.in:/etc/hyperledger/fabric-ca-server
   container_name: ca.ashwinihospital.co.in
   networks:
     - healthcare_network
