# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3.5"

networks:
  healthcare_network:
   name: healthcare_network

services:


  ca.ashwinihospital.co.in:
   image: hyperledger/fabric-ca:$IMAGE_TAG
   environment:
     - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
     - FABRIC_CA_SERVER_CA_NAME=ca.ashwinihospital.co.in
     - FABRIC_CA_SERVER_TLS_ENABLED=true
     - FABRIC_CA_SERVER_PORT=9054
     - FABRIC_CA_SERVER_CSR_HOSTS=ca.ashwinihospital.co.in,localhost
     - FABRIC_CA_SERVER_CSR_CN=ca.ashwinihospital.co.in
   ports:
     - "9054:9054"
   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
   volumes:
     - ../../../organizations/fabric-ca/ashwinihospital.co.in:/etc/hyperledger/fabric-ca-server
   container_name: ca.ashwinihospital.co.in
   networks:
     - healthcare_network
