
version: '3.5'

volumes:
  scsmsr.co.in:

networks:
  healthcare_network:
   name: healthcare_network

services:
  scsmsr.co.in:
    container_name: scsmsr.co.in
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=scsmsr.co.in
      - CORE_PEER_ADDRESS=scsmsr.co.in:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=scsmsr.co.in:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=scsmsr.co.in:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=scsmsr.co.in:7051
      - CORE_PEER_LOCALMSPID=SCSMSRMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../organizations/peerOrganizations/scsmsr.co.in/peers/scsmsr.co.in/msp:/etc/hyperledger/fabric/msp
        - ../../organizations/peerOrganizations/scsmsr.co.in/peers/scsmsr.co.in/tls:/etc/hyperledger/fabric/tls
        - scsmsr.co.in:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - healthcare_network